name: Bundle CI
on: [pull_request]

jobs:
  setup:
    name: 'Setup matrix'
    runs-on: ubuntu-22.04
    outputs:
      matrix: ${{ steps.set-matrix.outputs.output }}
    steps:
      - uses: 'actions/checkout@v4'
      - name: 'Generate matrix as JSON'
        id: 'set-matrix'
        uses: ./.github/reusable-steps
        with:
          call: test-matrix-json

  tests:
    runs-on: ubuntu-22.04
    needs: 'setup'

    strategy:
      fail-fast: false
      matrix:
        include: ${{ fromJson(needs.setup.outputs.matrix) }}

    steps:
      - uses: actions/checkout@v4
      - name: 'Run tests'
        uses: ./.github/reusable-steps
        with:
          call: test --php-version="${{ matrix.php-version }}" --symfony-version="${{ matrix.symfony-version || '>=5.4' }}" phpunit --dependency-version="${{ matrix.dependency-version || 'locked' }}" --minimum-stability="${{ matrix.minimum-stability || 'stable' }}" stdout
