on: [pull_request]
name: Static analysis

jobs:
  phpstan:
    name: PHPStan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: 'Run PHPStan'
        uses: ./.github/reusable-steps
        with:
          call: 'static phpstan'

  php-cs-fixer:
    name: PHP-CS-Fixer
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: 'Run PHP CS Fixer'
        uses: ./.github/reusable-steps
        with:
          call: 'static cs'

  psalm:
    name: Psalm
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: 'Run Psalm'
        uses: ./.github/reusable-steps
        with:
          call: 'static psalm'

  composer-normalize:
    name: Composer Normalize
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: 'Run Composer Normalize'
        uses: ./.github/reusable-steps
        with:
          call: 'static composer-normalize'
